### ISSUE TITLE
Users can unlock foreign locks in groupfolders

### ISSUE THREAD

**Issue by susnux** [nextcloud/files_lock#170] opened 2023-09-27 10:47 UTC
See https://github.com/nextcloud/files_lock/issues/169

But for this one it is a bug, as their is no real owner of the files.
The reason for this bug is still the same, but for groupfolders we should not assume any member a owner and allow them to unlock, but only the managers.

**Comment by susnux** [comment] 2023-09-27 22:14
As i wrote in the on the linked issue, this makes sense for user shares.
But for group folders it is weird.

**Comment by max-nextcloud** [comment] 2023-10-09 07:50
Fixed by #171

**Closed by max-nextcloud** 2023-10-09 07:50 UTC
Labels: bug, 0. Needs triage

**Comment by vincib** [comment] 2023-11-28 14:01
FYI, I have the following in the oc_files_lock table:

```
MariaDB@cloud1 [cloud8]> select * from oc_files_lock where file_id=1946631;
+------+----------------------------------+---------+-------------------------------------------------+------------+------+-------+-----+-------+
| id   | user_id                          | file_id | token                                           | creation   | type | scope | ttl | owner |
+------+----------------------------------+---------+-------------------------------------------------+------------+------+-------+-----+-------+
| 6393 | <email of user A> | 1946631 | files_lock/d438f017-95d8-402a-83be-47952d7f8e34 | 1701179522 |    0 |     0 |   0 |       |
```

and we are using redis as distributed / local & lock storage.

**Comment by max-nextcloud** [comment] 2023-12-05 10:40
> user B get a message : "File is currently locked by <email of user A>"

Sounds like the intended behavior to me. This issue was about user B being able to unlock the file despite it being locked by user A.

My impression is that there are a lot of different expectations as to how locks should behave. What's the behavior you would expect @vincib ?

**Comment by susnux** [comment] 2023-12-05 11:27
> Sounds like the intended behavior to me.

I agree I would also expect this behavior as the file is already locked

**Comment by camlafit** [comment] 2023-12-08 13:31
Hello

I think @vincib has miss an information, B try also to unlock the file.  As admin same error occurs.
In this cas behavoir expected should be to unlock the file.

**Comment by camlafit** [comment] 2023-12-23 17:33
Hello

We have continue to investigate.
This touble looks occurred when user A has only read permission. With desktop client locks looks applied anyway. 
Lock is not removed and block next user B with write permission.

Thanks a lot
