### ISSUE TITLE
Update 26.0.0 troubles

### ISSUE THREAD

**Issue by jayrope** [nextcloud/files_lock#119] opened 2023-02-23 11:26 UTC
Just a quick feedback, that update 26.0.0 applied to NC 25.0.3 turned Nextcloud into a blank page here. 
I ended up having to disable and delete files_lock via occ to get Nextcloud back working. 

From error log:  PHP Fatal error:  Trait "OCA\FilesLock\Tools\Traits\TStringTools" not found in /home/../../apps/files_lock/lib/Service/LockService.php on line 56

**Comment by enoch85** [comment] 2023-03-20 07:43
@szaimen Can you let the right people know about this? Feels like a showstopper for NC 26.

**Comment by small1** [comment] 2023-03-20 08:07
Tested the update on several nc25 based system and can not reproduce this one.

**Comment by joshtrichards** [comment] 2024-06-12 22:41
Closing due to inability to reproduce and lack of further reports. Maybe caching?

**Closed by joshtrichards** 2024-06-12 22:41 UTC
Labels: needs info
