### ISSUE TITLE
clicking 'Shared' reset locking status on front-end

### ISSUE THREAD

**Issue by daita** [nextcloud/files_lock#5] opened 2019-11-20 10:53 UTC
When I click on the 'Shared' link in the Inline Action the status of the lock is lost while displaying the right panel. Even the 'Unlock file' is changed to 'Lock file' (while the file is still lock as no request is sent to the back-end)

![issue_shared](https://user-images.githubusercontent.com/1038617/69233728-f9062080-0b7c-11ea-9a0d-1b01f763151a.gif)

**Comment by juliushaertl** [comment] 2019-11-26 17:33
@daita Can you still reproduce this? Doesn't happen for me.

**Comment by juliushaertl** [comment] 2019-12-18 17:35
Let me close this as I cannot reproduce it together with beta2.

**Closed by juliushaertl** 2019-12-18 17:35 UTC
